<a href="https://colab.research.google.com/github/Kylerovic11/58003-Linear-Algebra/blob/main/Vector%2C_Spaces%2C_and_Operating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Raw Vector
  

In [ ]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is',A)
print('Vector B is',B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [ ]:

### Checking shapes
### Shapes tells us how many rows and columns are there
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool.shape



In [3]:
#Size Dimention, Size

import numpy as np
ball1=np.array([1,2,3])
ball2=np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1)
print(ball)

[1 2 3]
[ 0  1 -1]
(3,)


Addition **bold text**

In [7]:
#Spaces = Addition
A = np.array ([4,3])
B = np.array ([2,-5])

R = np.add(A,B)

print (R)

[ 6 -2]


In [9]:
#subtraction
R1=np.subtract(A,B)
print(R1)
R2=np.subtract(B,A)
print(R2)


[2 8]
[-2 -8]


In [12]:
#scalar Product
S = np.array([2])
V = S*A
print (V)

[8 6]


In [21]:
#Dot Product
A = np.array([4,3])
B = np.array([[2]],[[-5]])

D = A*B

print (D)


TypeError: ignored

In [25]:
#property of matrix
#identity Matrix
c = np.eye(3,3)
print(c)

#zero Matrix
d = np.zeros([5,5])
print (d)

#full matrix
e = np.full ((3,3),7)
print (e)
#transpose matrix
f=np.transpose(A)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[4 3]
